name = "wechat-mp-automated-publisher"
main = "src/index.ts"
compatibility_date = "2024-02-22"

# Bindings
[ai]
binding = "AI"

# Environment variables
# [vars]
# APPID = "wxce886342ef86a0d7"
# APPSECRET = "76c330faaf69e373c2188db49c5b9ed6"

[triggers]
crons = [
  "30 21 * * *", # 21:30 UTC -> 08:00 Adelaide (FINANCE)
  "45 21 * * *", # 21:45 UTC -> 08:15 Adelaide (NASA)
  "0 22 * * *",  # 22:00 UTC -> 08:30 Adelaide (ARS)
  "15 22 * * *"  # 22:15 UTC -> 08:45 Adelaide (IMMIGRATION)
]
